/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structures.and.algorithms.java;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
