/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.util.Arrays;
import java.util.HashMap;
import java.util.regex.Pattern;

public class App {
    public static void main(String[] args) {



        Hashtable<Object> newHash = new Hashtable<>(3);

        newHash.add("s1", "malik");
        newHash.add("s2", "mahmoud");

        System.out.println(newHash.hash("s1"));
        System.out.println(newHash.contains("s1"));


        System.out.println(newHash.hash("s2"));
        System.out.println(newHash.contains("s2"));

        System.out.println(newHash.get("s1"));
        System.out.println(newHash.get("s2"));
        System.out.println(newHash.get("s3"));


        newHash.add("s3", "swayyed");
        System.out.println(newHash.hash("s3"));
        System.out.println(newHash.contains("s3"));
        System.out.println(newHash.get("s3"));

        newHash.add("s4", "collision");
        System.out.println(newHash.hash("s4"));
        System.out.println(newHash.contains("s4"));
        System.out.println(newHash.get("s4"));
        System.out.println(newHash.get("s1"));





//        System.out.println(newHash.nodesArraySize);
//        System.out.println(newHash.nodesArray[5].value);
//
        System.out.println(Arrays.toString(newHash.nodesArray));


        System.out.println(newHash.nodesArray[2].next);

//
        String text = "It was the best of times, it was the worst of times,";
        System.out.println(repeatedWord(text));

    }
    public static String  repeatedWord(String text){
        HashMap<String,Integer> array = new HashMap<>();
        String result = null;

        String[] arrayOfWords = text.split(" ");

        for (int i = 0; i < arrayOfWords.length; i++) {

            if (arrayOfWords[i].contains(",")){
                arrayOfWords[i] = deleteComaFromString(arrayOfWords[i]);
            }


            if (array.containsKey(arrayOfWords[i].toLowerCase())){
                result = arrayOfWords[i];
                break;
            }else{
                array.put(arrayOfWords[i].toLowerCase(),i);
            }
        }
        return result;
    }




    public static String deleteComaFromString(String str){
        str = str.substring(0, str.length() - 1);
        return str;
    }
}


