/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue;



public class Library {
    public static void main(String[] args) throws Exception {
        Stack  s1 = new Stack();
        s1.push("5");
        s1.push("7");
        s1.push("9");
        System.out.println(s1.toString());
        System.out.println(s1.isEmpty());
        s1.pop();
        System.out.println(s1.peek());


        Queue queue = new Queue();

        queue.enqueue("1");
        queue.enqueue("2");
        queue.enqueue("3");
        System.out.println(queue.toString());
        System.out.println(queue.peek());
   System.out.println(queue.dequeue());
        System.out.println(queue.isEmpty());








    }
}
