/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class Library {
    public static void main(String[] args) {


        BinarySearchTree<Integer> test = new BinarySearchTree<>(5);

        System.out.println(test.contains(4, test.root));


        test.root.leftRoot = new Node<>(3);
        test.root.rightRoot = new Node<>(6);

        test.add(4);

        System.out.println(test.contains(5,test.root));
        System.out.println(test.inOrder(test.root).toString());

    }
}
