/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class Library {
    public static void main(String[] args) {


        BinarySearchTree<Integer> test = new BinarySearchTree<>(5);

        System.out.println(test.contains(4, test.root));




        test.add(4);
        test.add(8);
        test.add(3);

        System.out.println(test.contains(5,test.root));
        System.out.println(test.inOrder(test.root).toString());


        System.out.println(test.Max());
    }
}
