/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.Test;

import static hashtable.App.repeatedWord;
import static junit.framework.TestCase.*;


public class AppTest {
    @Test public void appHasAGreeting() {


        //Adding a key/value to your hashtable results in the value being in the data structure
        Hashtable hashtable = new Hashtable(10);
        hashtable.add("s1","malik");
        assertTrue(hashtable.contains("s1"));



        //Retrieving based on a key returns the value stored
        assertEquals("malik",hashtable.get("s1"));


        //Successfully returns null for a key that does not exist in the hashtable

        assertEquals("requested key is not exist",hashtable.get("s2"));




        //Successfully handle a collision within the hashtable
        hashtable.add("a","the first");
        hashtable.add(97,"the second");

        assertEquals("the first",hashtable.nodesArray[7].value);
        assertEquals("the second",hashtable.nodesArray[7].next.value);




        //Successfully retrieve a value from a bucket within the hashtable that has a collision
        assertEquals("the first",hashtable.get("a"));



        //Successfully hash a key to an in-range value
        assertEquals(9,hashtable.hash("hi"));





    }
    //-------------------code challenge 31--------------------------


    @Test public void repeatedWordTest() {
        // testing for repeatedWord function

        String test = "Once upon a time, there was a brave princess who...";
        assertEquals("a", repeatedWord(test));

        String test2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        assertEquals("it", repeatedWord(test2));

        String test3 = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        assertEquals("summer", repeatedWord(test3));



        // testing if the string doesn't have a repeated words, it should return null

        String test4 = "I wish you enjoy";

        assertNull(repeatedWord(test4));

    }

}
