/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.Test;

import static junit.framework.TestCase.assertEquals;
import static junit.framework.TestCase.assertTrue;


public class AppTest {
    @Test public void appHasAGreeting() {


        //Adding a key/value to your hashtable results in the value being in the data structure
        Hashtable hashtable = new Hashtable(10);
        hashtable.add("s1","malik");
        assertTrue(hashtable.contains("s1"));



        //Retrieving based on a key returns the value stored
        assertEquals("malik",hashtable.get("s1"));


        //Successfully returns null for a key that does not exist in the hashtable

        assertEquals("requested key is not exist",hashtable.get("s2"));




        //Successfully handle a collision within the hashtable
        hashtable.add("a","the first");
        hashtable.add(97,"the second");

        assertEquals("the first",hashtable.nodesArray[7].value);
        assertEquals("the second",hashtable.nodesArray[7].next.value);




        //Successfully retrieve a value from a bucket within the hashtable that has a collision
        assertEquals("the first",hashtable.get("a"));



        //Successfully hash a key to an in-range value
        assertEquals(9,hashtable.hash("hi"));


    }
}
