/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
    }


    @Test public void testQuickSort(){
        int[] arr = {8,4,23,42,16,15};
        int[] result = {4,8,15,16,23,42};


        App.mergeSort(arr);

        assertArrayEquals(result,arr);
    }

}
