/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");


    }
    @Test void testMergingSort(){
        int[] testing = {8,4,23,42,16,15};
        int[] result = {4,8,15,16,23,42};
        assertEquals(Arrays.toString(result),Arrays.toString(App.mergeSort(testing)));

    }

}
