/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quick.sort;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;
import static quick.sort.App.quickSort;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testQuickSort(){
        int[] arr = {8,4,23,42,16,15};
        int[] result = {4,8,15,16,23,42};


        App.quickSort(arr, 0, arr.length - 1);

        assertArrayEquals(result,arr);
    }
}
