/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testEmptyLinked(){
        assertEquals(null, new LinkedList().head);
    }
    @Test public void testInsert(){
        LinkedList ls = new LinkedList();
        ls.insert(5);
        ls.insert(7);

        assertEquals(7, ls.head.value);
        
    }

    @Test void insertMultiple(){
        LinkedList ls = new LinkedList();
        ls.insert(1);
        ls.insert(3);
        ls.insert(2);
        assertEquals(3,ls.length,"the linked list should have length of 3");

    @Test public void testMultiInsert(){
        LinkedList ls = new LinkedList();
        
        ls.insert(7);
        ls.insert(3);
        ls.insert(8);
        String str = ls.toString();
        assertEquals("{8}->{3}->{7}->NUll",str.toString());
               
        
    }
    
    @Test public void testInclude(){
        LinkedList ls = new LinkedList();

        ls.insert(3);
        assertTrue("it has a", ls.includes(3));
    }

    @Test void tostringTest(){
        LinkedList ls = new LinkedList();
        ls.insert(1);
        ls.insert(3);
        ls.insert(23);
        assertEquals("{ 1 } ->{ 3 } ->{ 23 } ->NULL",ls.toString(),"should return the list ");
    }
}


