/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Insertion.Sort;

import org.junit.Test;

import java.sql.Array;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());


    }

    @Test public void testSort(){
        int[] arr = {8,4,23,42,16,15};
        int[] result = {4,8,15,16,23,42};


        App.insertionSort(arr);

        assertArrayEquals(result,arr);
    }
}
